language: python

python:
    - "3.5"

addons:
  firefox: "latest"

services:
  - docker

sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  - directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "export DJANGO_SETTINGS_MODULE=course_discovery.settings.test"
    - export PATH=$PATH:$PWD/node_modules/.bin
    - docker run --detach  --publish 9200:9200 --publish 9300:9300 elasticsearch:1.5.2

install:
    - pip install -U pip wheel codecov
    - make requirements
    - make requirements.js

before_script:
# Give Elasticsearch time to start
  - sleep 10

script:
    # Ensure documentation can be compiled
    - cd docs && make html && cd ..

    # Check if translation files are up-to-date
    - make validate_translations

    # Compile static assets and validate the code
    - make static -e DJANGO_SETTINGS_MODULE="course_discovery.settings.test"
    - make validate

after_success:
    - codecov
