version: "2"

services:
  course-discovery:
    ports:
      - "18381:18381"
      - "8381:8381"
      - "48381:48381"

  db:
    ports:
      - "3306:3306"

  es:
    ports:
      - "9200:9200"
      - "9300:9300"
