version: "2"

services:
  db:
    image: mysql:5.6
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "discov001"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "discovery"

  es:
    image: elasticsearch:1.5.2
    container_name: es

  memcache:
    image: memcached:1.4.24
    container_name: memcache

  course-discovery:
    # Uncomment this line to use the official course-discovery base image
    image: edxops/discovery:latest

    # Uncomment the next two lines to build from a local configuration repo
    # build: ../configuration/docker/build/discovery/

    container_name: course-discovery
    command: /edx/app/discovery/devstack.sh start
    depends_on:
      - "db"
      - "es"
      - "memcache"
    environment:
      TEST_ELASTICSEARCH_URL: "http://es:9200"
